Revert "agate: Add Xiaomi Parts" * Causes build errors: device/xiaomi/agate/parts/src/org/lineageos/settings/refreshrate/RefreshSettingsFragment.java:87: error: cannot find symbol         return inflater.inflate(R.layout.refresh_layout, container, false);                                         ^   symbol:   variable refresh_layout   location: class layout device/xiaomi/agate/parts/src/org/lineageos/settings/refreshrate/RefreshSettingsFragment.java:94: error: cannot find symbol         mAppsRecyclerView = view.findViewById(R.id.refresh_rv_view);                                                   ^   symbol:   variable refresh_rv_view   location: class id
*Revert for now until fixed
This reverts commit eaafff7467ab09f580ebe216e034271d23afa64e.

Change-Id: I45144754104df4d9c7e6d383a6c6fb7601622040
Signed-off-by: 1tovgar <tovgar@proton.me>